"""add name to users

Revision ID: b3c8e600ea46
Revises: 42183700fc46
Create Date: 2026-07-01 12:54:10.207265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c8e600ea46'
down_revision: Union[str, Sequence[str], None] = '42183700fc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1 — add as nullable so existing rows don't fail
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    
    # Step 2 — backfill existing rows with a default
    op.execute("UPDATE users SET name = email WHERE name IS NULL")
    
    # Step 3 — now make it non-null
    op.alter_column('users', 'name', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
